### ISSUE TITLE
Membuat API untuk Module Program Studi

### ISSUE THREAD

**Issue by jacky-htg** [jacky-htg/tugas-project-web-2#14]
- Sediakan api list program studi (seluruh field) yang dilengkapi dengan fitur pagination, sorting dan filtering.
- Sediakan api list program studi (hanya field id dan nama) tanpa pagination, dilengkapi dengan fitur filtering berdasarkan nama proghram studi. filter menggunakan like '$search%'
- Sediakan api get program studi by taruna.

**Comment by juldhais** [comment]
Untuk point "Sediakan api get program studi by taruna." sepertinya perlu menunggu modul taruna selesai.

**Comment by jacky-htg** [comment]
untuk data taruna bisa dibuat saja dulu inject via DB mas.
