### ISSUE TITLE
Membuat API untuk Modul Matakuliah

### ISSUE THREAD

**Issue by jacky-htg** [jacky-htg/tugas-project-web-2#17]
- Sediakan api list matakuliah (seluruh field) yang dilengkapi dengan fitur pagination, sorting dan filtering.
- Sediakan api list matakuliah  (hanya field id dan nama) tanpa pagination, dilengkapi dengan fitur filtering berdasarkan nama matakuliah. filter menggunakan like '$search%'

**Comment by rudypriyanto** [comment]
tadi sudah saya add udh keupdate apa blm ya mas

**Comment by jacky-htg** [comment]
iya sudah mas. thanks
