### ISSUE TITLE
Modul Authentication

### ISSUE THREAD

**Issue by jacky-htg** [jacky-htg/tugas-project-web-2#31]
LOGIN : 
- halaman untuk publik
- field : email dan password
- validasi email : required | email format | exist in DB
- validasi password : required | verify password with user db.
- sanitasi input email dan password
- pasang captcha
- ada link forgot password
- simpan session user_id

LOGOUT : 
- halaman untuk admin
- destroy session

**Comment by ecepbustanularifin** [comment]
Mas rizal, ini cara merubah status nya jadi todo atau in progress gimana ya? apa emang saya gabisa ubah?

**Comment by jacky-htg** [comment]
bisa mas, geser saja tiketnya melalui board project https://github.com/users/jacky-htg/projects/1/views/1?layout=board

**Comment by jacky-htg** [comment]
untuk login dan logout sdh saya buat ya mas, tapi masih perlu adjustment :
- tampilan form login perlu dipercantik
- tambahkan captcha
- tambahkan link forgot password
