### ISSUE TITLE
Membuat Module Kota

### ISSUE THREAD

**Issue by jacky-htg** [jacky-htg/tugas-project-web-2#5]
- Sediakan halaman List menggunakan datatable
- Sediakan halaman create new kota
- Sediakan halaman update kota
- Sediakan halaman delete kota.

**Comment by jejensuwaji** [comment]
kalau lihat code yang sudah selesai bagaimana caranya?

**Comment by jacky-htg** [comment]
untuk akses kode bisa dilihat dibranch main ya mas @jejensuwaji 
https://github.com/jacky-htg/tugas-project-web-2
kalau ada kesulitan dengan git, nanti bisa diganedkan training git 1x pertemuan.
