### ISSUE TITLE
Implementasi lookup menggunakan select2 pada transkrip nilai

### ISSUE THREAD

**Issue by jacky-htg** [jacky-htg/tugas-project-web-2#61]
- saat ini field taruna pada create damn update transkript nilai masih berupa input free text.
- ubah field taruna pada create dan update transkrip nilai menjadi lookup menggunakan select2
- sudah ada contoh implementasi, karena pada halaman tersebut, field ijazah dan program studi sudah dalam bentuk lookup select2

**Comment by jejensuwaji** [comment]
baik saya coba
